"""
    publication_theme()

Sets up a paper quality theme
"""
function publication_theme()
    Theme(fontsize = 35,
          font = "CMU",
          resolution = (1152, 864),
          backgroundcolor = :white,
          figure_padding = (0, 40, 0, 20),
          linewidth = 5.0,
          palette = (color = ["#4263eb", "#f03e3e", "#f76707", "#099268", "#5f3dc4",
                         "#fcc419",
                         "#c2255c", "#1098ad", "#cf6db0", "#74b816"],),
          Axis = (aspect = nothing,
                  backgroundcolor = :white,
                  spinewidth = 1.0,
                  titlesize = 38,
                  xgridstyle = nothing,
                  xgridwidth = 1.0,
                  xgridcolor = RGBAf(0, 0, 0, 0.2),
                  xminorgridstyle = :dot,
                  xminorgridwidth = 1.5,
                  xminorgridcolor = RGBAf(0, 0, 0, 0.15),
                  xminortickcolor = :black,
                  xminorticks = IntervalsBetween(2),
                  xminorticksize = -7.5,
                  xminortickwidth = 1.0,
                  xminorticksvisible = true,
                  xticksmirrored = true,
                  xlabelsize = 40,
                  xlabelpadding = 10.0,
                  xtickalign = 1,
                  xticksize = 15,
                  xticklabelpad = 10,
                  ygridstyle = nothing,
                  ygridwidth = 1.0,
                  ygridcolor = RGBAf(0, 0, 0, 0.2),
                  yminorgridstyle = :dot,
                  yminorgridwidth = 1.5,
                  yminorgridcolor = RGBAf(0, 0, 0, 0.15),
                  yminortickcolor = :black,
                  yminorticks = IntervalsBetween(2),
                  yminorticksize = -7.5,
                  yminortickwidth = 1.0,
                  yminorticksvisible = true,
                  yticksmirrored = true,
                  ylabelsize = 40,
                  ylabelpadding = 5.0,
                  ytickalign = 1,
                  yticksize = 15,
                  yticklabelpad = 10,
                  xlabel = L"x",
                  ylabel = L"y",
                  xgridvisible = false,
                  ygridvisible = false,
                  xminorgridvisible = false,
                  yminorgridvisible = false),
          Legend = (bgcolor = (:white, 1),
                    framecolor = (:black, 0.8),
                    padding = (10, 10, 8, 8),
                    patchlabelgap = 25,
                    patchsize = (70, 20),
                    margin = (0, 0, 0, 0)),
          Colorbar = (bottomspinevisible = true,
                      minorticksvisible = false,
                      width = 30,
                      ticksize = 10,
                      tickalign = 0,
                      ticklabelpad = 7.5,
                      spinewidth = 0.5),
          Axis3 = (aspect = (1, 1, 2 / 3),
                   azimuth = 1.275π,
                   elevation = π / 8,
                   perspectiveness = 0.0,
                   protrusions = 0.0,
                   viewmode = :fit,
                   xgridvisible = true,
                   xgridwith = 1.5,
                   xlabeloffset = 50,
                   ygridvisible = true,
                   ygridwith = 1.5,
                   ylabeloffset = 50,
                   zgridvisible = true,
                   zgridwith = 1.5,
                   zlabeloffset = 50))
end

"""
    publication_dark_theme()

Sets up a paper quality theme (dark version)
"""
function publication_dark_theme()
    Theme(fontsize = 35,
          font = "CMU",
          textcolor = :white,
          resolution = (1152, 864),
          backgroundcolor = :black,
          figure_padding = (0, 40, 0, 20),
          linewidth = 5.0,
          palette = (color = ["#4263eb", "#f03e3e", "#f76707", "#099268", "#5f3dc4",
                         "#fcc419",
                         "#c2255c", "#1098ad", "#cf6db0", "#74b816"],),
          Axis = (aspect = nothing,
                  backgroundcolor = :black,
                  spinewidth = 1.0,
                  titlesize = 38,
                  titlecolor = :white,
                  xgridstyle = nothing,
                  xgridwidth = 1.0,
                  xgridcolor = RGBAf(255, 255, 255, 0.2),
                  xminorgridstyle = :dot,
                  xminorgridwidth = 1.5,
                  xminorgridcolor = RGBAf(255, 255, 255, 0.15),
                  xminortickcolor = :white,
                  xminorticks = IntervalsBetween(2),
                  xminorticksize = -7.5,
                  xminortickwidth = 1.0,
                  xminorticksvisible = true,
                  xticksmirrored = true,
                  xlabelsize = 40,
                  xlabelpadding = 10.0,
                  xlabelcolor = :white,
                  xtickalign = 1,
                  xticksize = 15,
                  xticklabelpad = 10,
                  xtickcolor = :white,
                  xticklabelcolor = :white,
                  ygridstyle = nothing,
                  ygridwidth = 1.0,
                  ygridcolor = RGBAf(255, 255, 255, 0.2),
                  yminorgridstyle = :dot,
                  yminorgridwidth = 1.5,
                  yminorgridcolor = RGBAf(255, 255, 255, 0.15),
                  yminortickcolor = :white,
                  yminorticks = IntervalsBetween(2),
                  yminorticksize = -7.5,
                  yminortickwidth = 1.0,
                  yminorticksvisible = true,
                  yticksmirrored = true,
                  ylabelsize = 40,
                  ylabelpadding = 5.0,
                  ylabelcolor = :white,
                  ytickalign = 1,
                  yticksize = 15,
                  ytickcolor = :white,
                  yticklabelpad = 10,
                  yticklabelcolor = :white,
                  xlabel = L"x",
                  ylabel = L"y",
                  xgridvisible = false,
                  ygridvisible = false,
                  xminorgridvisible = false,
                  yminorgridvisible = false,
                  topspinecolor = :white,
                  rightspinecolor = :white,
                  leftspinecolor = :white,
                  bottomspinecolor = :white),
          Legend = (bgcolor = (:black, 1),
                    framecolor = (:white, 0.8),
                    padding = (10, 10, 8, 8),
                    patchlabelgap = 25,
                    patchsize = (70, 20),
                    margin = (0, 0, 0, 0),
                    labelcolor = :white),
          Colorbar = (bottomspinevisible = true,
                      minorticksvisible = false,
                      width = 30,
                      tickcolor = :white,
                      ticksize = 10,
                      tickalign = 0,
                      ticklabelpad = 7.5,
                      spinewidth = 0.5),
          Axis3 = (aspect = (1, 1, 2 / 3),
                   azimuth = 1.275π,
                   elevation = π / 8,
                   perspectiveness = 0.0,
                   protrusions = 0.0,
                   viewmode = :fit,
                   xgridvisible = true,
                   xgridwith = 1.5,
                   xlabeloffset = 50,
                   ygridvisible = true,
                   ygridwith = 1.5,
                   ylabeloffset = 50,
                   zgridvisible = true,
                   zgridwith = 1.5,
                   zlabeloffset = 50,
                   titlecolor = :white,
                   xgridcolor = RGBAf(1, 1, 1, 0.12),
                   ygridcolor = RGBAf(1, 1, 1, 0.12),
                   zgridcolor = RGBAf(1, 1, 1, 0.12),
                   xspinecolor_1 = :white,
                   xspinecolor_2 = :white,
                   xspinecolor_3 = :white,
                   yspinecolor_1 = :white,
                   yspinecolor_2 = :white,
                   yspinecolor_3 = :white,
                   zspinecolor_1 = :white,
                   zspinecolor_2 = :white,
                   zspinecolor_3 = :white,
                   topspinecolor = :white,
                   xtickcolor = :white,
                   ytickcolor = :white,
                   ztickcolor = :white,
                   bottomspinecolor = :white,
                   tickcolor = :white))
end

fullscreen() = Theme(figure_padding = (0, 0, 0, 0))
